name: Style
on: 
  pull_request:
    paths:
      - '**.php'
  push:
    paths:
      - '**.php'
jobs:
  style:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@master #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.3
          extension-csv: mbstring, dom, fileinfo, mysql, zip
          coverage: xdebug #optional
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Install Composer dependencies
        run: |
            composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Run fix:style
        run: |
          export PATH="$HOME/.composer/vendor/bin:$PATH"
          ./vendor/bin/pint

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply style changes
          branch: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
